#!/bin/sh

echo "notes."

initdir () {
	mkdir -p ~/notes/
	rm -r ~/.config/notes.sh > /dev/null 2>&1
	mkdir -p ~/.config && mkdir -p ~/.config/notes.sh
	echo "$HOME/notes/" >> ~/.config/notes.sh/config
	}

customdir () {
	read -r -p "custom directory [/home/aadi/notes/]: " customdir
	mkdir $customdir
	rm ~/.config/notes.sh/config && echo $customdir >> ~/.config/notes.sh/config
	}

dir=$(cat $HOME/.config/notes.sh/config)

halp() {
	echo "notes.sh is a simple note taking tool."
	echo
	echo "syntax: notes [-i|n|l|r|h]"
	echo "options:"
	echo "i     init notes.sh config."
	echo "n     make a new note."
	echo "l     list all notes."
	echo "r     delete a note."
	echo "c     use a custom dir."
	echo "h     print help."
	echo
	}

newnote() {
	read -r -p "name of your note: " name
	touch $dir$name
	echo $name >> $dir$name
	read -r -p "date: " date
	echo $date >> $dir$name
	echo "---" >> $dir$name	
	"${EDITOR:-vim}" $dir$name
	}

listnotes() {
	echo ""
	ls $dir
	}

removenote() {
	rm $dir$rmname && echo "removed $rmname"
	}

while getopts ":hnlicr:" option; do
	case $option in
		h) 
			halp
			exit;;
		n)
			newnote;;
		l)
			listnotes;;
		i)
			initdir;;
		c)
			customdir;;
		r)
			rmname=$OPTARG
			removenote;;
		\?)
			newnote;;
	esac
done

